POST http://localhost:5000/api/room/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNmYjkyYTRlZTAxYjRiYzcyNDBkYWEiLCJ1c2VyTmFtZSI6ImFkbWluIiwicGVybWlzc2lvbnMiOnsiX2lkIjoiNjY1ZWNmZDkzMDM3ZGZkNzdkYmM2NmYyIiwibmFtZSI6IkFkbWluIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwicG9zaXRpb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjI3OjA1Ljk3N1oiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjI3OjA1Ljk3N1oiLCJfX3YiOjB9LCJpYXQiOjE3MTc0ODk3NjN9.vu6OYnun4yDLdxgjYHmab3FXp5g3MwFYe85KUfD53zo

{
    "name": "Phòng 4",
    "description": ""
  
}


###
GET http://localhost:5000/api/room/getRoomUserApprove/666d6916649cf0e2e21d8535
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZlYWJhYmI1YWU4Yzg2MWViNTYxZjYiLCJ1c2VyTmFtZSI6IlBo4bqhbSBWxINuIFRyxrDhu51uZyIsInBlcm1pc3Npb25zIjp7Il9pZCI6IjY2NmVhODQyYjVhZThjODYxZWI1NjEwNyIsIm5hbWUiOiJOaMOibiB2acOqbiIsInN0YXR1cyI6MSwicGVybWlzc2lvbiI6WyJyZWFkIl0sInBvc2l0aW9uIjpbInJlYWQiXSwicm9vbSI6WyJyZWFkIl0sInNpbmdsZSI6WyJjcmVhdGUiLCJyZWFkIl0sInNpbmdsZVR5cGUiOlsicmVhZCJdLCJ1c2VyIjpbInJlYWQiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0xNlQwODo1NDoyNi45NjZaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xNlQwOToxMjo1NS44MTJaIiwiX192IjowfSwiaWF0IjoxNzE4NTMwMDExfQ.ACuRawZjzsaK6yUcK8s27kOZlLjJuWsGuz7jOJZWoyA


###
GET http://localhost:5000/api/room/getAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZlYWJhYmI1YWU4Yzg2MWViNTYxZjYiLCJ1c2VyTmFtZSI6IlBo4bqhbSBWxINuIFRyxrDhu51uZyIsInBlcm1pc3Npb25zIjp7Il9pZCI6IjY2NmVhODQyYjVhZThjODYxZWI1NjEwNyIsIm5hbWUiOiJOaMOibiB2acOqbiIsInN0YXR1cyI6MSwicGVybWlzc2lvbiI6WyJyZWFkIl0sInBvc2l0aW9uIjpbInJlYWQiXSwicm9vbSI6WyJyZWFkIl0sInNpbmdsZSI6WyJjcmVhdGUiLCJyZWFkIl0sInNpbmdsZVR5cGUiOlsicmVhZCJdLCJ1c2VyIjpbInJlYWQiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0xNlQwODo1NDoyNi45NjZaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xNlQwOToxMjo1NS44MTJaIiwiX192IjowfSwiaWF0IjoxNzE4NTMwMDExfQ.ACuRawZjzsaK6yUcK8s27kOZlLjJuWsGuz7jOJZWoyA



###
PUT http://localhost:5000/api/room/update/651fbdb3ba02fe686fcbfea1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYmQ2NmJhMDJmZTY4NmZjYmZlOWMiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBwaMOybmcgYmFuIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbInJlYWQiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1NzkwNzB9.PNciiNtUf7P0nyBDtViLgy_zE1nT62RizEjWWMTVPDw


{
    "name": "Phòng nhân sự",
    "description": ""
  
}
###
DELETE  http://localhost:5000/api/room/deleteRoom/666cfb762ce638f214aa6952
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYmQ2NmJhMDJmZTY4NmZjYmZlOWMiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBwaMOybmcgYmFuIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbInJlYWQiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1NzkwNzB9.PNciiNtUf7P0nyBDtViLgy_zE1nT62RizEjWWMTVPDw
