POST http://localhost:5000/api/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNmYjkyYTRlZTAxYjRiYzcyNDBkYWEiLCJ1c2VyTmFtZSI6ImFkbWluIiwicGVybWlzc2lvbnMiOnsiX2lkIjoiNjY1ZWNmZDkzMDM3ZGZkNzdkYmM2NmYyIiwibmFtZSI6IkFkbWluIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwicG9zaXRpb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjI3OjA1Ljk3N1oiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjI3OjA1Ljk3N1oiLCJfX3YiOjB9LCJpYXQiOjE3MTc1NzAzMzl9.cX1blS_CS-LQ1V96Sv3yE65e_a_cTNZRszaYEDUsJ7U

{
    "name":"phamtruong",
    "email":"vantruongvip25@gmail.com",
    "password":"1",
    "room":"663fb9f94ee01b4bc7248bd9",
    "permissions":"665ecfd93037dfd77dbc66f2",
    "positions":"663fba314ee01b4bc724ae48"
    
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"123"
}
###
Put http://localhost:5000/api/users/update/666002e9161692c7517d4a18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYwMDJlOTE2MTY5MmM3NTE3ZDRhMTgiLCJ1c2VyTmFtZSI6InB2dGJvdGR5IiwicGVybWlzc2lvbnMiOnsiX2lkIjoiNjY1ZWQyYzAzMDM3ZGZkNzdkYmM2NzBkIiwibmFtZSI6Ik5ow6JuIHZpw6puIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbInJlYWQiXSwic2luZ2xlIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjM5OjI4LjAxNVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjM5OjI4LjAxNVoiLCJfX3YiOjB9LCJpYXQiOjE3MTc1Njg2NzZ9.cqcgRO_c6zL2T5EQNJ-XsAlAYJBwrlJjOcxr7E2Mqyk

{
   
  
    "sex": "",
    "phone":"0975128913",
    "birthday": "14/10/2001"
}


###
GET  http://localhost:5000/api/users/getAllUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFjZmUzZjk4NTA1MTNjODBiOTNkZmEiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFjZDc0NTEzMDU2YjRmOTRhY2Y4NzkiLCJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJwb3NpdGlvbiI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvb20iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJzaW5nbGUiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSIsImFwcHJvdmUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJfX3YiOjB9LCJpYXQiOjE3MTY4ODExNzUsImV4cCI6MTcxNjk2NzU3NX0.e2aHNKEzacDtuSydK1RhK_tMuo6f5GaQ-JNqkB_tnNk


###
GET  http://localhost:5000/api/users/getUser/66600d32af0ba9021065c7ee
Content-Type: application/json


###
POST http://localhost:5000/api/users/forgotPassword
Content-Type: application/json

{
    "email" :"pvtbotdy2k1@gmail.com"
}

###
POST http://localhost:5000/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjU1OGQ4ODdhMDBiNGRhMjkyMmM3OTkiLCJ1c2VyTmFtZSI6InB2dGJvdGR5IiwicGVybWlzc2lvbnMiOnsiX2lkIjoiNjUxZDM1ZGYzNGVkNjhkNDFiYjFkOWJjIiwibmFtZSI6IlF14bqjbiBsw70gY2jhu6ljIHYiLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsicmVhZCJdLCJwb3NpdGlvbiI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvb20iOlsicmVhZCJdLCJzaW5nbGUiOlsicmVhZCJdLCJzaW5nbGVUeXBlIjpbInJlYWQiXSwidXNlciI6WyJyZWFkIiwidXBkYXRlIl0sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMDRUMDk6NTI6MzEuMjgwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTAtMDZUMDg6MjA6NTAuMTM5WiIsIl9fdiI6MH0sImlhdCI6MTcxNjk1ODYzMCwiZXhwIjoxNzE3MDQ1MDMwfQ.jAGhIQ3yCmZLn3-ToDNCqrIETpRUL9V2SrpU7CU7-cE

###
GET  http://localhost:5000/api/users/loadUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYwMGY2OWU0NTA4ZTk4N2FiNGIwYWUiLCJ1c2VyTmFtZSI6InB2dGJvdGR5IiwicGVybWlzc2lvbnMiOnsiX2lkIjoiNjY1ZWQyYzAzMDM3ZGZkNzdkYmM2NzBkIiwibmFtZSI6Ik5ow6JuIHZpw6puIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbInJlYWQiXSwic2luZ2xlIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjM5OjI4LjAxNVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjM5OjI4LjAxNVoiLCJfX3YiOjB9LCJpYXQiOjE3MTc1ODE2NTh9._j8FqvcVsuPYMRymk9ZovNXm9GZgO3NFbmuEWvYAzuY


###
post http://localhost:5000/api/users/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYwMGY2OWU0NTA4ZTk4N2FiNGIwYWUiLCJ1c2VyTmFtZSI6InB2dGJvdGR5IiwicGVybWlzc2lvbnMiOnsiX2lkIjoiNjY1ZWQyYzAzMDM3ZGZkNzdkYmM2NzBkIiwibmFtZSI6Ik5ow6JuIHZpw6puIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbInJlYWQiXSwic2luZ2xlIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjM5OjI4LjAxNVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTA0VDA4OjM5OjI4LjAxNVoiLCJfX3YiOjB9LCJpYXQiOjE3MTc2NDU3ODV9._5pu6PMuC0rcQ7gWFMHwoo3eUbKLeikmruYoUH1ykJ0


{
   
  
    "password":"mot",
    "newPassword":"1"
}